config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'items#index'
  
  resources :items do
    collection do
      get 'category_lists'
      get 'confirmation'
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_children_edit', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_category_children_render', defaults: { format: 'json' }
      get 'get_category_grandchildren_render', defaults: { format: 'json' }

    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_category_children_render', defaults: { format: 'json' }
      get 'get_category_grandchildren_render', defaults: { format: 'json' }
      get 'category_item_lists'
      get 'confirmation'
      post 'buy'
      get 'card'
    end
  end

  resources :users, only: [:index, :new] do
    collection do
      get 'logout'
    end
  end

  resources :cards, only: [:new, :show, :destroy, :edit] do
    collection do
      post 'pay', to: 'cards#pay'

    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category
  # belongs_to :comment
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true
  extend ActiveHash::Associations::ActiveRecordExtensions
  # belongs_to :user
  belongs_to :seller, class_name: 'User', foreign_key: 'seller_id'
  belongs_to_active_hash :condition
  belongs_to_active_hash :postage_payer
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :shipping_method
  belongs_to_active_hash :preparation
  belongs_to_active_hash :size

  validates :item_images, presence: true
  validates :name, presence: true, length: { maximum: 40 }
  validates :text, presence: true, length: { maximum: 1000 }
  validates :category, presence: true
  validates :condition_id, presence: true
  validates :postage_payer_id, presence: true
  validates :prefecture_id, presence: true
  validates :shipping_method_id, presence: true
  validates :preparation_id, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}

  def self.search(search)
    if search
      Item.where('items.name LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :move_to_index, except: [:index, :show, :category_lists, :category_item_lists]
  before_action :set_item, only: [:edit, :update, :show, :destroy, :confirmation, :buy]
  before_action :set_category_links, only: :category_item_lists
  before_action :set_card, only: [:confirmation, :buy]
  before_action :set_category, only: [:new, :create]

  def index
    @items = Item.all.order(id: :desc)
    ladies = Category.find(1)
    @ladies = Item.where(category_id: ladies.subtree).order(id: :desc)
    mens = Category.find(199)
    @mens = Item.where(category_id: mens.subtree).order(id: :desc)
    electricalappliances = Category.find(889)
    @electricalappliances = Item.where(category_id: electricalappliances.subtree).order(id: :desc)
    hobby = Category.find(617)
    @hobby = Item.where(category_id: hobby.subtree).order(id: :desc)
  end

  def show
    @otheritems = Item.all.limit(12).order(id: :desc)
    @item = Item.find(params[:id])
    @it = Item.joins(:user).find(params[:id])
    @category = Item.joins(:category).find(params[:id])
    @item_category_id = @item[:category_id]
    @item_category = Category.find(@item_category_id)
    unless @item_category[:ancestry] == nil
      @item_children_category = Category.find(@item_category.parent_id)
      @item_parent_category = Category.find(@item_category.root_id)
    end
  end

  def new
    @item = Item.new
    @item.item_images.new
    @category_parent_array = Category.where(ancestry: nil)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品が出品されました"
      redirect_to root_path
    else
      @item.item_images.new(item_images_params)
      @category_parent_array = Category.where(ancestry: nil)
      render :new
    end
  end

  def destroy
    @item = Item.find(params[:id])
    if @item.destroy
      flash[:notice] = "商品は削除されました"
      redirect_to root_path
    else
      redirect_to item_path
    end
  end

  def edit
    @category_parent_array = Category.where(ancestry: nil)
  end

  def update
    if @item.update(item_upgrade_params)
      redirect_to root_path
    else
      redirect_back fallback_location: edit_item_path, flash:{alerting: @item.errors.full_messages}
    end
  end

  def category_lists
    @parents = Category.where(ancestry: nil)
  end
  
  def confirmation
    @address = User.where(id: current_user.id).first
    if @card.present?
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
      # Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)

      @card_brand = @default_card_information.brand
      case @card_brand
      when "Visa"
        @card_image = "card_visa_b.gif"
      when "JCB"
        @card_image = "card_jcb_b.gif"
      when "MasterCard"
        @card_image = "card_master_b.gif"
      when "American Express"
        @card_image = "card_amex_b.gif"
      when "Diners Club"
        @card_image = "card_diners_b.gif"
      when "Discover"
        @card_image = "card_dc_b.gif"
      end
    end
  end

  def buy
    if @item.update(buyer_id: params[:buyer_id])
        # redirect_to root_path
      Payjp::Charge.create(
      :amount => @item.price, 
      :customer => @card.customer_id, 
      :currency => 'jpy', #日本円
      )

      redirect_to confirmation_item_path, notice: '購入が完了されました'

    else
      render :confirmation
    end

    # @address = User.where(id: current_user.id).first

  end

  def category_item_lists
    @items = @category.set_items
    @items = @items.where(buyer_id: nil).order(created_at: :desc)
  end

  def search
    @items = Item.search(params[:keyword])
  end

  # privateの中に入れないでください
  def get_category_children
    @category_children = Category.find(params[:parent_name]).children
  end

  def get_category_children_edit
    @category_children_edit = Category.find(params[:category_id]).children
  end

  # privateの中に入れないでください
  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end


  private
  def item_params
    params.require(:item).permit(:name, :price, :text, :brand, :category_id, :size_id, :condition_id, :postage_payer_id, :prefecture_id, :shipping_method_id, :preparation_id, :seller_id, item_images_attributes: [:image]).merge(user_id: current_user.id)
  end

  def item_upgrade_params
    params.require(:item).permit(:name, :price, :text, :brand, :category_id, :size_id, :condition_id, :postage_payer_id, :prefecture_id, :shipping_method_id, :preparation_id, :seller_id, item_images_attributes: [:image, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def item_images_params
    params.permit(:image)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end  

  def set_category_links
    @category = Category.find(params[:id])
    if @category.has_children?
      @category_links = @category.children
    else
      @category_links = @category.siblings
    end
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_category
    @category_parent_array = Category.where(ancestry: nil)
  end


  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_confirmation-footer.html.haml
// フッター
.Footer
  %ul.Footer__ul
    %li.Footer__li 
      = link_to "プライバシーポリシー", root_path
    %li.Footer__li 
      = link_to "メルカリ利用規約", root_path
    %li.Footer__li 
      = link_to "特定商取引に関する表記", root_path
  = link_to root_path do
    = image_tag("logo-white.png", alt: "logo", class: "Footer__image")
  %p.Footer__copyright © FURIMA, Inc.

app/views/items/_confirmation-header.html.haml
// ヘッダー
.Header
  .Header__logo 
    = link_to root_path do
      = image_tag("logo.png", alt: "logo", class: "Header__logo-image")

app/views/items/_footer.html.haml
.Footer
  %ul.Footer__contents
    %li.Footer__contents-content
      %h2.Footer__contents-subtitle FURIMAについて
      %ul.Footer__contents-ul

        %li.Footer__contents-li
          = link_to '会社概要(運営会社)', root_path ,class: "Footer＿contents-a"
        %li.Footer__contents-li
          = link_to 'プライバシーボリシー', root_path ,class: "Footer＿contents-a"
        %li.Footer__contents-li
          = link_to 'FURIMA利用規約', root_path ,class: "Footer＿contents-a"
        %li.Footer__contents-li
          = link_to 'ポイントに関する特約', root_path ,class: "Footer＿contents-a"
        
    %li.Footer__contents-content
      %h2.Footer__contents-subtitle FURIMAを見る 
      %ul.Footer__contents-ul

        %li.Footer__contents-li
          = link_to 'カテゴリー一覧', root_path ,class: "Footer＿contents-a"
        %li.Footer__contents-li
          = link_to 'ブランド一覧', root_path ,class: "Footer＿contents-a"
       

    %li.Footer__contents-content
      %h2.Footer__contents-subtitle ヘルプ&ガイド 
      %ul.Footer__contents-ul

        %li.Footer__contents-li
          = link_to 'FURIMAガイド', root_path ,class: "Footer＿contents-a"
        %li.Footer__contents-li
          = link_to 'FURIMAロゴ利用ガイドライン', root_path ,class: "Footer＿contents-a"
        %li.Footer__contents-li
          = link_to 'お知らせ', root_path ,class: "Footer＿contents-a"
        
  = link_to root_path, class: "Footer__logo" do
    = image_tag("logo-white.png", alt: "logo", class: "Footer__logo-image")
  %p.Footer__logo-text @ FURIMA

app/views/items/_header.html.haml
.Header
  .Header__top
    = link_to root_path, class: "Logo" do
      = image_tag("logo.png", alt: "logo", class: "Logo__image")
    
    = form_with url: search_items_path, method: :get, class: "Search", local:true do |form|
      = form.text_field :keyword, placeholder: "キーワードから探す", class: "Search__inputText"
      = form.submit  value: "",class: "Search__submitBtn", type:"submit"

  .Header__bottom
    = link_to '全ての商品一覧', category_lists_items_path ,class: "Product-table"
    .User
    - if user_signed_in?
      %h2
        現在 #{current_user.nickname} さんがログインしています
      = link_to "マイページ", users_path, class: "User__Mypage"
    - else
      %h2 現在ログインしていません
      = link_to 'ログイン', new_user_session_path ,class: "User__login"
      = link_to '新規会員登録', new_user_registration_path ,class: "User__registration"

app/views/items/_putup-item.html.haml
.putup-item-top
  = link_to root_path do
    = image_tag "logo.png", size: "185x49"
.putup-item-middle
  = form_with model:@item, local:true do |f|
    = render 'layouts/error_messages', model: f.object
    .putup-item-middle__content
      
      .putup-item-middle__content__form
        .putup-item-middle__content__form__upload
          .putup-item-middle__content__form__upload__block
            %h3.putup-item-middle__content__index__title
              出品画像
            %p.putup-item-middle__content__index__essential 必須
          %p 最大5枚までアップロードできます
          .post__drop__box__container
            .prev-content
            .label-content
              %label{for: "item_item_images_attributes_0_image", class: "label-box", id: "label-box--0"}
                %pre.label-box__text-visible クリックしてファイルをアップロード
            .hidden-content
              = f.fields_for :item_images do |i|
                = i.file_field :image, class: "hidden-field"
                
                %input{class:"hidden-field", type: "file", name: "item[item_images_attributes][1][image]", id: "item_item_images_attributes_1_image" }
                %input{class:"hidden-field", type: "file", name: "item[item_images_attributes][2][image]", id: "item_item_images_attributes_2_image" }
                %input{class:"hidden-field", type: "file", name: "item[item_images_attributes][3][image]", id: "item_item_images_attributes_3_image" }
                %input{class:"hidden-field", type: "file", name: "item[item_images_attributes][4][image]", id: "item_item_images_attributes_4_image" }
                  

    .putup-item-middle__content
      .putup-item-middle__content__index
        .putup-item-middle__content__index__title
          商品名
        .putup-item-middle__content__index__essential
          必須
      =f.text_field :name, class: "putup-item-middle__content__item-name", placeholder: "40文字まで", maxlength: "40"
    
    .putup-item-middle__content
      .putup-item-middle__content__index
        .putup-item-middle__content__index__title
          商品の説明
        .putup-item-middle__content__index__essential
          必須
      =f.text_area :text, class: "putup-item-middle__content__item-description", placeholder: "商品の説明（必須 1,000文字以内）", rows: "7", maxlength: "1000"
    
    - if controller.action_name == 'new'
      #category_box.putup-item-middle__content
        .putup-item-middle__content__index
          .putup-item-middle__content__index__title
            カテゴリー
          .putup-item-middle__content__index__essential
            必須
        #parent_box
          = f.collection_select :category_id, @category_parent_array, :id, :name, {include_blank: "選択してください", selected: @item.category&.root_id}, class: "select parent_category_box", id: "parent_category"
        #children_box
        #grandchildren_box
      #size_box.putup-item-middle__content
        .putup-item-middle__content__index
          .putup-item-middle__content__index__title
            サイズ
          .putup-item-middle__content__index__essential
            任意
        .pulldown#size_selectbox
          =f.collection_select :size_id, Size.all, :id, :name, {prompt: "選択してください"}, {class: "select"}
    - else
      - if @item.category_id.present?
        #category_box.putup-item-middle__content
          .putup-item-middle__content__index
            .putup-item-middle__content__index__title
              カテゴリー
            .putup-item-middle__content__index__essential
              必須
          #parent_box_render
            = f.collection_select :category_id, @category_parent_array, :id, :name, {include_blank: "選択してください", selected: @item.category&.root_id}, class: "select", id: "parent_category_render"
          #children_box_render
            = f.collection_select :category_id, @item.category.root.children, :id, :name, {include_blank: "選択してください", selected: @item.category.parent_id}, class: "select", id: "children_category_render"
          #grandchildren_box_render
            = f.collection_select :category_id, @item.category.siblings, :id, :name, {include_blank: "選択してください", selected: @item.category.id}, class: "select", id: "grandchildren_category_render"
        #size_box_render.putup-item-middle__content
          .putup-item-middle__content__index
            .putup-item-middle__content__index__title
              サイズ
            .putup-item-middle__content__index__essential
              任意
          .pulldown#size_selectbox
            =f.collection_select :size_id, Size.all, :id, :name, {prompt: "選択してください"}, {class: "select"}
      - else
        #category_box.putup-item-middle__content
          .putup-item-middle__content__index
            .putup-item-middle__content__index__title
              カテゴリー
            .putup-item-middle__content__index__essential
              必須
          #parent_box_render
            = f.collection_select :category_id, @category_parent_array, :id, :name, {include_blank: "選択してください"}, class: "select", id: "parent_category_render"
          #children_box_render 
            = f.collection_select :category_id, {}, :id, :name, {include_blank: "選択してください"}, class: "select", id: "children_category_render"
          #grandchildren_box_render
            = f.collection_select :category_id, {}, :id, :name, {include_blank: "選択してください"}, class: "select", id: "grandchildren_category_render"
        #size_box_render.putup-item-middle__content
          .putup-item-middle__content__index
            .putup-item-middle__content__index__title
              サイズ
            .putup-item-middle__content__index__essential
              任意
          .pulldown#size_selectbox
            =f.collection_select :size_id, Size.all, :id, :name, {prompt: "選択してください"}, {class: "select"}
    .putup-item-middle__content
      .putup-item-middle__content__index
        .putup-item-middle__content__index__title
          ブランド
        .putup-item-middle__content__index__essential
          任意
      =f.text_field :brand, class: "select", placeholder: "入力してください"
    
    .putup-item-middle__content
      .putup-item-middle__content__index
        .putup-item-middle__content__index__title
          商品の状態
        .putup-item-middle__content__index__essential
          必須
      = f.collection_select :condition_id, Condition.all, :id, :name, {prompt: "選択してください"}, {class: "select"}
    
    .putup-item-middle__content
      .putup-item-middle__content__index
        .putup-item-middle__content__index__title
          配送料の負担
        .putup-item-middle__content__index__essential
          必須
      = f.collection_select :postage_payer_id, PostagePayer.all, :id, :name, {prompt: "選択してください"}, {class: "select"}
    
    .putup-item-middle__content
      .putup-item-middle__content__index
        .putup-item-middle__content__index__title
          発送元の地域
        .putup-item-middle__content__index__essential
          必須
      = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "選択してください"}, {class: "select"}
    
    .putup-item-middle__content
      .putup-item-middle__content__index
        .putup-item-middle__content__index__title
          発送方法
        .putup-item-middle__content__index__essential
          必須
      = f.collection_select :shipping_method_id, ShippingMethod.all, :id, :name, {prompt: "選択してください"}, {class: "select"}

    .putup-item-middle__content
      .putup-item-middle__content__index
        .putup-item-middle__content__index__title
          発送までの日数
        .putup-item-middle__content__index__essential
          必須
      = f.collection_select :preparation_id, Preparation.all, :id, :name, {prompt: "選択してください"}, {class: "select"}
    
    .CalcField
      .CalcField__index
        .CalcField__index__Field
          .CalcField__index__Field__title
            販売価格
          .CalcField__index__Field__essential
            必須
        .CalcField__index__Form
          .CalcField__index__Form__En ¥
          = f.number_field :price, class: "CalcField__index__Form__Item-value", placeholder: "0", autocomplete: "off", min: 300, max: 9999999
      .CalcField__Alart 300以上9999999以下で入力してください
      .CalcField__Fee
        .CalcField__Fee__Left 販売手数料（10%）
        %span#SalesFee.CalcField__Fee__Right ー
      %hr.Border
      .CalcField__Fee
        .CalcField__Fee__Left 販売利益
        %span#SalesProfit.CalcField__Fee__Right ー
    .putup-item-bottom
      .Button
        = f.hidden_field :seller_id, value: current_user.id
        = f.submit "出品する", class: "Button__Form__Red"
        %button.Button__Form__Gray{type: "button"} 下書きに保存
        =link_to users_path do
          マイページ

.ItemFooter
  .ItemFooter__Upper
    %ul.ItemFooter__Upper__Box
      %li.ItemFooter__Upper__Box__List
        =link_to "#" do
          プライバシーポリシー
      %li.ItemFooter__Upper__Box__List
        =link_to "#" do
          利用規約
      %li.ItemFooter__Upper__Box__List
        =link_to "#" do
          特定商品に関する表記
  .ItemFooter__Lower
    = link_to root_path do
      = image_tag "logo.png", size: "100x25"
    %h3 @FURIMA, Inc.

app/views/items/_search_result.html.haml
.Search_container
  .Search
    .h2 検索結果
    .Search__results
      - @items.each do |item|
        = link_to item_path(item) do
          .Search__results__list
            .Search__results__list__image
              - item.item_images.each do |image|
                =image_tag image.image.to_s, class: 'picture'
            .Search__results__list__image__price
              ¥
              = item.price
              .Search__results__list__image__text
                -# = item.show_soldout_item(item)
            .Search__results__list__text
              .Search__results__list__content
                = item.name
                .Search__results__list__content__hidden

app/views/items/_side_bar.html.haml
.SideBar
  .SideBar__Group
    %ul.SideBar__ListBox
      %li.SideBar__List
        = link_to "マイページ", users_path
      %li.SideBar__List
        = link_to "お知らせ", "#"
      %li.SideBar__List
        = link_to "やることリスト", "#"
      %li.SideBar__List
        = link_to "いいね!一覧", "#"
      %li.SideBar__List
        = link_to "出品する", new_item_path
      %li.SideBar__List
        = link_to "下書き一覧", "#"
      %li.SideBar__List
        = link_to "出品した商品-出品中", "#"
      %li.SideBar__List
        = link_to "出品した商品-取引中", "#"
      %li.SideBar__List
        = link_to "出品した商品-売却済み", "#"
      %li.SideBar__List
        = link_to "購入した商品-取引中", "#"
      %li.SideBar__List
        = link_to "購入した商品-過去の取引", "#"
      %li.SideBar__List
        = link_to "ニュース一覧", "#"
      %li.SideBar__List
        = link_to "評価一覧", "#"
      %li.SideBar__List
        = link_to "ガイド", "#"
      %li.SideBar__List
        = link_to "お問い合わせ", "#"
    %h3.SideBar__Title
      メルペイ
    %ul.SideBar__ListBox
      %li.SideBar__List
        = link_to "売上・振込申請", "#"
      %li.SideBar__List
        = link_to "ポイント", "#"
    %h3.SideBar__Title
      設定
    %ul.SideBar__ListBox
      %li.SideBar__List
        = link_to "プロフィール", "#"
      %li.SideBar__List
        = link_to "発送元", "#"
      %li.SideBar__List
        = link_to "支払い方法", new_card_path
      %li.SideBar__List
        = link_to "メール/パスワード", "#"
      %li.SideBar__List
        = link_to "本人情報", "#"
      %li.SideBar__List
        = link_to "電話番号の確認", "#"
      %li.SideBar__List
        = link_to "ログアウト", logout_users_path

app/views/items/buy.html.haml
%h2 購入が完了しました！
%p Apple MacBook Pro 13インチ
%p ¥135,000(送料込み)

app/views/items/category_item_lists.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FleamarketSample79e
    = csrf_meta_tags
    = csp_meta_tag
    -# = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'modules/TopPage', 'modules/category_item_lists'
    = javascript_include_tag 'application'

-# 上記class名重複防止の記述

= render "header"

.main
  .main_container
    .main_lists
      .title_box
        %h1.title
          = "#{@category.name}の商品一覧"
        %ul.category__child.category__list
          - @category_links.each do |category|
            = link_to category.name, category_item_lists_item_path(category)

      .image_lists
        - @items.each do |item|
          = link_to item_path(item.id), class: "Picup-item" do
            = image_tag item.item_images[0].image.to_s
            .Picup-item__body
              %h3 
                =item.name
              .Picup-item__details
                %ul.Picup-item__ul
                  %li.Picup-item__li
                    =item.price
                    円
                  %li.Picup-item__li
                    = icon('fas', 'star')
                    0  
                %p.Picup-item__note (税込)

=render "footer-img"

=render "footer"

app/views/items/category_lists.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FleamarketSample79e
    = csrf_meta_tags
    = csp_meta_tag
    -# = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'modules/TopPage', 'modules/category_lists'
    = javascript_include_tag 'application'
    %script{:src => "http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js", :type => "text/javascript"}
    :javascript
      $(function(){
        $('a.parents').each(function(i){
          $(this).attr('href', '#parent_name' + (i+1));
        });
        $('li.parents_title').each(function(i){
          $(this).attr('id', 'parent_name' + (i+1));
        });
        // #で始まるアンカーをクリックした場合に処理
        $('a[href^=#]').click(function() {
            // スクロールの速度
            var speed = 0; // ミリ秒
            // アンカーの値取得
            var href= $(this).attr("href");
            // 移動先を取得
            var target = $(href == "#" || href == "" ? 'html' : href);
            // 移動先を数値で取得
            var position = target.offset().top;
            // スムーススクロール
            $('body,html').animate({scrollTop:position}, speed, 'swing');
            return false;
        });
      });

-# 上記class名重複防止の記述

= render "header"

.main
  .main_container
    .main_index
      .parent_category
        - @parents.each do |parent|
          %li.parents
            %a.parents #{parent.name}

        %ul.categories
          - @parents.each do |parent|
            %li.parents_title= link_to "#{parent.name}", category_item_lists_item_path(parent)
            %ul.categories__children
              - parent.children.each do |child|
                %li.childern= link_to "#{child.name}", category_item_lists_item_path(child)
                %ul.categories__grandchildren
                  - child.children.each do |grandchild|
                    %li= link_to "#{grandchild.name}", category_item_lists_item_path(grandchild)
              %ul.return_top
                %li
                  %a.button{href: "#index"} ▲ トップに戻る

=render "footer-img"

=render "footer"

app/views/items/edit.html.haml
%html
  %head
    = stylesheet_link_tag 'modules/items'
    = javascript_include_tag 'application'

.wrapper
  = render "putup-item-edit"
  

app/views/items/search.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FleamarketSample79e
    = csrf_meta_tags
    = csp_meta_tag
    -# = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'modules/items'
    = javascript_include_tag 'application'


    = render "header"

    .Search-Wrapper
      = render 'search-detail'
      = render 'search_result'