config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'items#index'
  
  resources :items do
    collection do
      get 'category_lists'
      get 'confirmation'
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_children_edit', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_category_children_render', defaults: { format: 'json' }
      get 'get_category_grandchildren_render', defaults: { format: 'json' }

    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_category_children_render', defaults: { format: 'json' }
      get 'get_category_grandchildren_render', defaults: { format: 'json' }
      get 'category_item_lists'
      get 'confirmation'
      post 'buy'
      get 'card'
    end
  end

  resources :users, only: [:index, :new] do
    collection do
      get 'logout'
    end
  end

  resources :cards, only: [:new, :show, :destroy, :edit] do
    collection do
      post 'pay', to: 'cards#pay'

    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  require "payjp"
  before_action :set_card, only: [:destroy, :show]


  def edit
  end

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to card_path(current_user.id) if card.exists?
  end

  def pay #payjpとCardのデータベース作成
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
    # Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    #保管した顧客IDでpayjpから情報取
    if params['payjp-token'].present?
      customer = Payjp::Customer.create(
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      
      flash[:notice] = "登録が完了しました"
      if @card.save
        redirect_to card_path(current_user.id)
      
      else
        redirect_to new_cards_path
      end

    else
      redirect_to new_card_path
    end
  end

  def destroy #PayjpとCardデータベースを削除
    if @card.present?
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
      # Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
      flash[:notice] = "削除されました"
    else
    end
      redirect_to new_card_path
  end

  def show #Cardのデータpayjpに送り情報を取り出す
    if @card.present?
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
      # Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)

      @card_brand = @default_card_information.brand
      case @card_brand
      when "Visa"
        @card_image = "card_visa_b.gif"
      when "JCB"
        @card_image = "card_jcb_b.gif"
      when "MasterCard"
        @card_image = "card_master_b.gif"
      when "American Express"
        @card_image = "card_amex_b.gif"
      when "Diners Club"
        @card_image = "card_diners_b.gif"
      when "Discover"
        @card_image = "card_dc_b.gif"
      end
 
    else
      redirect_to new_card_path 

    end
  end

  private

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_new.html.haml
.R-Content
  %h2.R-Content__Title
    クレジットカード情報入力
  .FormContent
    = form_with url: pay_cards_path, method: :post, id: "charge-form", name: "inputForm",local: true do |form|
      .UserInfo
        .CardNumber
          %label
            カード番号
          %span
            必須
          = text_field_tag "card_number", "", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
        
        .CardImage
          = image_tag "cards/card_visa_b.gif",width:'50',height:'50', alt:'master-card'
          = image_tag "cards/card_master_b.gif",width:'50',height:'50', alt:'master-card'
          = image_tag "cards/card_jcb_b.gif",width:'50',height:'50', alt:'master-card'
          = image_tag "cards/card_amex_b.gif",width:'50',height:'50', alt:'master-card'
          = image_tag "cards/card_diners_b.gif",width:'50',height:'50', alt:'master-card'

      .UserInfo
        .CardNumber
          %label
            有効期限
          %span
            必須
        %select#exp_month{name: "exp_month", type: "text"}
          %option{:value => "01"} 01
          %option{:value => "02"} 02
          %option{:value => "03"} 03
          %option{:value => "04"} 04
          %option{:value => "05"} 05
          %option{:value => "06"} 06
          %option{:value => "07"} 07
          %option{:value => "08"} 08
          %option{:value => "09"} 09
          %option{:value => "10"} 10
          %option{:value => "11"} 11
          %option{:value => "12"} 12
        
        %span
          月

        %select#exp_year{name: "exp_year", type: "text"}
          %option{:value => "2020"} 20
          %option{:value => "2021"} 21
          %option{:value => "2022"} 22
          %option{:value => "2023"} 23
          %option{:value => "2024"} 24
          %option{:value => "2025"} 25
          %option{:value => "2026"} 26
          %option{:value => "2027"} 27
          %option{:value => "2028"} 28
          %option{:value => "2029"} 29
          %option{:value => "2030"} 30

        %span
          年

      .UserInfo
        .CardNumber
          %label
            セキュリティーコード
          %span
            必須
        = text_field_tag "cvc", "", class: "securityInput", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
 
      
        .SequirtyInfo
          %span
            -# カード裏面の番号とは？


        
        #card_token
        %br
        = form.submit "登録する", id: "token_submit"

app/views/cards/_show.html.haml
.show
  .show__frame
    .show__frame__title
      %h2 登録クレジットカード情報
    .credit_card__list

      .credit_card__list__frame
        .credit_card_info
          -#   # メソッドで定義した@card_srcを呼び出し
          -#   # 画像をcardsというフォルダを作り、入れておく
          .credit_card_info__numbers
            .credit_card_info__brand
            = image_tag "cards/#{@card_image}",width:'66',height:'50', alt:'master-card'

            .number_lits
              .number
                -# Pay.jpから取得したカード番号の末尾４桁を取得
              = "**** **** **** " + @default_card_information.last4
              .expiration_date
                .expiration_date__title
                  有効期限
                .expiration_date__info
                  - exp_month = @default_card_information.exp_month.to_s
                  - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                  = exp_month + " / " + exp_year
          .destroy__function
            .destroy__function__linktop
              = form_tag(root_path, method: :get) do
                %button.top-btn トップページ
                
            .destroy__function__link
              -# # 削除ボタンを作成、押すとdestroyメソッドが働くように
              = form_tag(card_path(current_user.id), method: :delete, id: 'charge-form',  name: "inputForm") do
                %input{ type: "hidden", name: "card_id", value: "" }
                %button.delete-btn 削除する

app/views/cards/_side_bar.html.haml
.SideBar
  .SideBar__Group
    %ul.SideBar__ListBox
      %li.SideBar__List
        = link_to "マイページ", users_path
      %li.SideBar__List
        = link_to "お知らせ", "#"
      %li.SideBar__List
        = link_to "やることリスト", "#"
      %li.SideBar__List
        = link_to "いいね!一覧", "#"
      %li.SideBar__List
        = link_to "出品する", new_item_path
      %li.SideBar__List
        = link_to "下書き一覧", "#"
      %li.SideBar__List
        = link_to "出品した商品-出品中", "#"
      %li.SideBar__List
        = link_to "出品した商品-取引中", "#"
      %li.SideBar__List
        = link_to "出品した商品-売却済み", "#"
      %li.SideBar__List
        = link_to "購入した商品-取引中", "#"
      %li.SideBar__List
        = link_to "購入した商品-過去の取引", "#"
      %li.SideBar__List
        = link_to "ニュース一覧", "#"
      %li.SideBar__List
        = link_to "評価一覧", "#"
      %li.SideBar__List
        = link_to "ガイド", "#"
      %li.SideBar__List
        = link_to "お問い合わせ", "#"
    %h3.SideBar__Title
      メルペイ
    %ul.SideBar__ListBox
      %li.SideBar__List
        = link_to "売上・振込申請", "#"
      %li.SideBar__List
        = link_to "ポイント", "#"
    %h3.SideBar__Title
      設定
    %ul.SideBar__ListBox
      %li.SideBar__List
        = link_to "プロフィール", "#"
      %li.SideBar__List
        = link_to "発送元", "#"
      %li.SideBar__List
        = link_to "支払い方法", new_card_path
      %li.SideBar__List
        = link_to "メール/パスワード", "#"
      %li.SideBar__List
        = link_to "本人情報", "#"
      %li.SideBar__List
        = link_to "電話番号の確認", "#"
      %li.SideBar__List
        = link_to "ログアウト", logout_users_path

app/views/cards/edit.html.haml
クレカ変更

app/views/cards/new.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FleamarketSample79e
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'modules/cards'
    = javascript_include_tag 'application'
    = render 'layouts/notifications'

.Body_Block
  .Wrapper
    = render "side_bar"
    = render "new"

app/views/cards/show.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FleamarketSample79e
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'modules/cards'
    = render 'layouts/notifications'

.Body_Block
  .Wrapper
    = render "side_bar"
    = render "show"